min_version = "2026.4.15"

[env]
_.path = [
  "/opt/homebrew/opt/llvm@20/bin",
  "/usr/local/opt/llvm@20/bin",
]

[tools]
zig = "0.15.1"

[tasks.check]
description = "Check that the Matcha compiler compiles"
run = "zig build check"

[tasks.build]
description = "Build the Matcha compiler"
run = "zig build"

[tasks.test]
description = "Run Matcha compiler tests"
run = "zig build test"

[tasks.build-compiler]
description = "Build an optimized matcha compiler binary"
run = "zig build -Doptimize=ReleaseFast"
