#!/usr/bin/env bash
# This file was generated by AI.
set -euo pipefail

repository_root=$(CDPATH='' cd -- "$(dirname -- "$0")/../.." && pwd)
temporary_directory=$(mktemp -d "${TMPDIR:-/tmp}/matcha-release-tools.XXXXXX")
trap 'rm -rf "$temporary_directory"' EXIT

fail() {
    printf 'FAIL: %s\n' "$*" >&2
    exit 1
}

assert_contains() {
    local expected=$1
    local file=$2
    grep -Fq "$expected" "$file" || fail "$file does not contain: $expected"
}

make_compiler_fixture() {
    local root=$1
    mkdir -p "$root/scripts/release" "$root/matcha-compiler"
    cp "$repository_root/scripts/release/set-compiler-version" "$root/scripts/release/"
    cp "$repository_root/scripts/release/prepare-candidate" "$root/scripts/release/"
    cp "$repository_root/scripts/release/publish-version" "$root/scripts/release/"
    cp "$repository_root/scripts/release/validate-published-release" "$root/scripts/release/"
    cat > "$root/matcha-compiler/build.zig" <<'EOF'
pub fn build() void {
    build_options.addOption([]const u8, "version", "0.1.1");
}
EOF
    cat > "$root/matcha-compiler/build.zig.zon" <<'EOF'
.{
    .version = "0.1.1",
}
EOF
    cat > "$root/matcha-compiler/README.md" <<'EOF'
Matcha is a fast-moving `v0.1.1` hobby language project.
EOF
}

compiler_fixture="$temporary_directory/compiler"
make_compiler_fixture "$compiler_fixture"

current_version=$("$compiler_fixture/scripts/release/set-compiler-version" --current)
[[ $current_version == 0.1.1 ]] || fail "unexpected current version: $current_version"

cp -R "$compiler_fixture" "$temporary_directory/compiler-before-dry-run"
dry_run_output=$("$compiler_fixture/scripts/release/set-compiler-version" --dry-run 0.1.2)
printf '%s\n' "$dry_run_output" | grep -Fq '0.1.2' || fail "dry run did not show target version"
diff -ru "$temporary_directory/compiler-before-dry-run" "$compiler_fixture" >/dev/null || fail "dry run changed fixture files"

"$compiler_fixture/scripts/release/set-compiler-version" 0.1.2
assert_contains '"version", "0.1.2"' "$compiler_fixture/matcha-compiler/build.zig"
assert_contains '.version = "0.1.2"' "$compiler_fixture/matcha-compiler/build.zig.zon"
assert_contains "fast-moving \`v0.1.2\` hobby language project" "$compiler_fixture/matcha-compiler/README.md"

if "$compiler_fixture/scripts/release/set-compiler-version" v0.1.3 >/dev/null 2>&1; then
    fail "accepted version with leading v"
fi

"$compiler_fixture/scripts/release/set-compiler-version" 0.1.3-pr.12.1
if "$compiler_fixture/scripts/release/set-compiler-version" 0.1.3-pr.01 >/dev/null 2>&1; then
    fail "accepted prerelease identifier with a leading zero"
fi

mismatched_fixture="$temporary_directory/compiler-mismatched"
make_compiler_fixture "$mismatched_fixture"
sed 's/0\.1\.1/0.1.0/' "$mismatched_fixture/matcha-compiler/build.zig.zon" > "$mismatched_fixture/matcha-compiler/build.zig.zon.tmp"
mv "$mismatched_fixture/matcha-compiler/build.zig.zon.tmp" "$mismatched_fixture/matcha-compiler/build.zig.zon"
if "$mismatched_fixture/scripts/release/set-compiler-version" 0.1.2 >/dev/null 2>&1; then
    fail "accepted mismatched compiler versions"
fi

duplicate_fixture="$temporary_directory/compiler-duplicate"
make_compiler_fixture "$duplicate_fixture"
printf '    .version = "0.1.1",\n' >> "$duplicate_fixture/matcha-compiler/build.zig.zon"
if "$duplicate_fixture/scripts/release/set-compiler-version" 0.1.2 >/dev/null 2>&1; then
    fail "accepted duplicate package version declarations"
fi

prepare_fixture="$temporary_directory/compiler-prepare"
make_compiler_fixture "$prepare_fixture"
git -C "$prepare_fixture" init -q -b main
git -C "$prepare_fixture" config user.name Test
git -C "$prepare_fixture" config user.email test@example.com
git -C "$prepare_fixture" add .
git -C "$prepare_fixture" commit -qm Initial
prepare_output="$temporary_directory/prepare-output"
GITHUB_EVENT_NAME=pull_request \
GITHUB_OUTPUT="$prepare_output" \
GITHUB_REF=refs/pull/7/merge \
GITHUB_REPOSITORY=mario-nowak/matcha \
GITHUB_RUN_ATTEMPT=2 \
PR_NUMBER=7 \
RUNNER_TEMP="$temporary_directory" \
    "$prepare_fixture/scripts/release/prepare-candidate"
assert_contains 'version=0.0.0-pr.7.2' "$prepare_output"
assert_contains '"version", "0.0.0-pr.7.2"' "$prepare_fixture/matcha-compiler/build.zig"

publish_fixture="$temporary_directory/compiler-publish"
publish_origin="$temporary_directory/compiler-publish.git"
make_compiler_fixture "$publish_fixture"
git -C "$publish_fixture" init -q -b main
git -C "$publish_fixture" config user.name Test
git -C "$publish_fixture" config user.email test@example.com
git -C "$publish_fixture" add .
git -C "$publish_fixture" commit -qm Initial
git init --bare -q "$publish_origin"
git -C "$publish_fixture" remote add origin "$publish_origin"
git -C "$publish_fixture" push -qu origin main
base_sha=$(git -C "$publish_fixture" rev-parse HEAD)
"$publish_fixture/scripts/release/publish-version" 0.1.2 matcha-compiler-v0.1.2 "$base_sha"
release_sha=$(git -C "$publish_fixture" rev-parse HEAD)
[[ $release_sha != "$base_sha" ]] || fail "publish script did not create a release commit"
[[ $(git --git-dir="$publish_origin" rev-parse refs/heads/main) == "$release_sha" ]] || fail "publish script did not push main"
[[ $(git --git-dir="$publish_origin" rev-parse refs/tags/matcha-compiler-v0.1.2) == "$release_sha" ]] || fail "publish script did not push tag"
"$publish_fixture/scripts/release/publish-version" 0.1.2 matcha-compiler-v0.1.2 "$release_sha"

fake_bin="$temporary_directory/fake-bin"
published_release_json="$temporary_directory/published-release-source.json"
validator_output="$temporary_directory/validator-output"
mkdir -p "$fake_bin"
cat > "$fake_bin/gh" <<'EOF'
#!/bin/sh
cat "$FAKE_RELEASE_JSON"
EOF
chmod +x "$fake_bin/gh"
cat > "$published_release_json" <<'EOF'
{
  "tagName": "matcha-compiler-v0.1.2",
  "isDraft": false,
  "isPrerelease": true,
  "assets": [
    {"name": "matcha-compiler-v0.1.2-linux-x86_64.tar.gz"},
    {"name": "matcha-compiler-v0.1.2-macos-arm64.tar.gz"},
    {"name": "SHA256SUMS.txt"}
  ]
}
EOF
FAKE_RELEASE_JSON="$published_release_json" \
GITHUB_OUTPUT="$validator_output" \
GH_TOKEN=test \
PATH="$fake_bin:$PATH" \
RUNNER_TEMP="$temporary_directory" \
    "$publish_fixture/scripts/release/validate-published-release" matcha-compiler-v0.1.2 mario-nowak/matcha
assert_contains 'tag=matcha-compiler-v0.1.2' "$validator_output"
assert_contains 'version=0.1.2' "$validator_output"

package_fixture="$temporary_directory/package-repository"
package_output="$temporary_directory/package-output"
package_work="$temporary_directory/package-work"
mkdir -p "$package_fixture/matcha-compiler/zig-out/bin" "$package_fixture/matcha-compiler/zig-out/lib" "$package_output" "$package_work"
cat > "$package_fixture/matcha-compiler/zig-out/bin/matcha" <<'EOF'
#!/bin/sh
[ "${1:-}" = "--version" ] || exit 1
printf '0.1.2\n'
EOF
chmod +x "$package_fixture/matcha-compiler/zig-out/bin/matcha"
printf 'runtime\n' > "$package_fixture/matcha-compiler/zig-out/lib/libmatcha_runtime.a"
(
    cd "$package_output"
    MATCHA_REPOSITORY_ROOT="$package_fixture" "$repository_root/scripts/release/package-compiler" 0.1.2 macos arm64 "$package_work"
)
macos_archive="$package_output/matcha-compiler-v0.1.2-macos-arm64.tar.gz"
linux_archive="$package_output/matcha-compiler-v0.1.2-linux-x86_64.tar.gz"
[[ -f "$macos_archive" ]] || fail "package script did not create macOS archive"
cp "$macos_archive" "$linux_archive"
"$repository_root/scripts/release/generate-checksums" 0.1.2 "$package_output"
[[ $(wc -l < "$package_output/SHA256SUMS.txt" | tr -d ' ') == 2 ]] || fail "checksum script did not create two entries"
assert_contains 'matcha-compiler-v0.1.2-macos-arm64.tar.gz' "$package_output/SHA256SUMS.txt"
assert_contains 'matcha-compiler-v0.1.2-linux-x86_64.tar.gz' "$package_output/SHA256SUMS.txt"

formula_fixture="$temporary_directory/matcha-lang.rb"
cat > "$formula_fixture" <<'EOF'
class MatchaLang < Formula
  version "0.1.1"

  on_macos do
    on_arm do
      url "https://github.com/mario-nowak/matcha/releases/download/matcha-compiler-v0.1.1/matcha-compiler-v0.1.1-macos-arm64.tar.gz"
      sha256 "8a430719f890804078d4dd53025a3ce1b64c399aeef8a0762e0cb68ccd56af93"
    end
  end
end
EOF

formula_before="$temporary_directory/matcha-lang-before.rb"
cp "$formula_fixture" "$formula_before"
new_sha=1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef
formula_dry_run=$("$repository_root/scripts/release/set-homebrew-formula-version" --dry-run "$formula_fixture" 0.1.2 "$new_sha")
printf '%s\n' "$formula_dry_run" | grep -Fq 'matcha-compiler-v0.1.2-macos-arm64.tar.gz' || fail "formula dry run did not show target URL"
cmp "$formula_before" "$formula_fixture" >/dev/null || fail "formula dry run changed fixture"

"$repository_root/scripts/release/set-homebrew-formula-version" "$formula_fixture" 0.1.2 "$new_sha"
assert_contains 'version "0.1.2"' "$formula_fixture"
assert_contains 'matcha-compiler-v0.1.2/matcha-compiler-v0.1.2-macos-arm64.tar.gz' "$formula_fixture"
assert_contains "sha256 \"$new_sha\"" "$formula_fixture"

if "$repository_root/scripts/release/set-homebrew-formula-version" "$formula_fixture" 0.1.3 invalid >/dev/null 2>&1; then
    fail "accepted invalid formula checksum"
fi
if "$repository_root/scripts/release/set-homebrew-formula-version" "$formula_fixture" 0.1.3-pr.01 "$new_sha" >/dev/null 2>&1; then
    fail "accepted invalid formula version"
fi

printf 'Release tool tests passed.\n'
