pub const TokenKind = union(enum) {
    // Keywords
    Val,
    Var,
    If,
    Else,
    Match,
    Not,
    And,
    Or,
    Loop,
    Leave,
    Continue,
    While,
    For,
    In,
    Item,
    Return,
    Structure,
    // Punctuation
    LeftParenthesis,
    RightParenthesis,
    LeftBrace,
    RightBrace,
    LeftBracket,
    RightBracket,
    Assign,
    PlusAssign,
    MinusAssign,
    AsteriskAssign,
    FatArrow,
    EqualEqual,
    NotEqual,
    LessThan,
    LessThanOrEqual,
    GreaterThan,
    GreaterThanOrEqual,
    Colon,
    Semicolon,
    Plus,
    Minus,
    Asterisk,
    Slash,
    Comma,
    Dot,
    //
    Identifier: []const u8,
    IntLiteral: i64,
    RealLiteral: f64,
    BooleanLiteral: bool,
    StringLiteral: []const u8,
    //
    EndOfFile,
};

pub const Token = struct {
    line: usize,
    column: usize,
    offsetInSource: usize,
    lenInSource: u32,
    kind: TokenKind,
};
