const diagnostics = @import("diagnostics");

pub const TokenKind = union(enum) {
    // Keywords
    val,
    @"var",
    @"if",
    @"else",
    match,
    not,
    @"and",
    @"or",
    loop,
    leave,
    @"continue",
    @"while",
    @"for",
    in,
    item,
    @"return",
    structure,
    @"union",
    // Punctuation
    left_parenthesis,
    right_parenthesis,
    left_brace,
    right_brace,
    left_bracket,
    right_bracket,
    assign,
    plus_assign,
    minus_assign,
    asterisk_assign,
    fat_arrow,
    equal_equal,
    not_equal,
    less_than,
    less_than_or_equal,
    greater_than,
    greater_than_or_equal,
    colon,
    semicolon,
    plus,
    minus,
    asterisk,
    slash,
    comma,
    dot,
    //
    identifier: []const u8,
    int_literal: i64,
    real_literal: f64,
    boolean_literal: bool,
    string_literal: []const u8,
    //
    end_of_file,
};

pub const Token = struct {
    module_id: diagnostics.ModuleId,
    line: usize,
    column: usize,
    offset_in_source: usize,
    length_in_source: u32,
    kind: TokenKind,
};
